plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs

# There's a bug at the moment with the new appDir in NextJS where a buuld fails with the error:
# Error: EROFS: read-only filesystem, open '/node_modules/next/dist/server/initialize-require-hook.js'
# https://github.com/vercel/next.js/issues/42427
# nodeLinker: pnp
nodeLinker: node-modules
