# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

jobs:
  build-nextjs:
    docker:
      - image: cimg/node:18.15-browsers
    steps:
      - node/run:
          yarn-run: workspace @foundation/www-nextjs build


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-nextjs-workflow:
    jobs:
      - build-nextjs
