# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

# jobs:
#   build-nextjs:
#     docker:
#       - image: cimg/node:18.15-browsers
#     steps:
#       - node/run:
#           yarn-run: workspace @foundation/www-nextjs build
jobs:
  post-nextjs-stats:
    docker:
      - image: cimg/node:18.15-browsers
    steps:
      - run:
          name: Post Stats to GitHub PR
          command: |
            sudo apt-get install jq

            pr_response=$(curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH&state=open" \
              -u $GH_USER:$GH_TOKEN)

            if [ $(echo $pr_response | jq length) -eq 0 ]; then
              echo "No PR found to update"
            else
              pr_comment_url=$(echo $pr_response | jq -r ".[]._links.comments.href")
            fi

            curl --location --request POST "$pr_comment_url" \
              -u $GH_USER:$GH_TOKEN \
              --header 'Content-Type: application/json' \
              --data-raw '{
                  "body": "This would be the data to add"
                }'



# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-nextjs-workflow:
    jobs:
      - node/run:
          version: 18.15.0
          pkg-manager: yarn
          yarn-run: build:nextjs
      - post-nextjs-stats
